name: solaredge
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy --workspace --all-features --tests -- -D warnings
